import React, { useState } from 'react';
import './privacy-policy.css';

const PrivacyPolicy = () => {
  const [activeSection, setActiveSection] = useState(null);

  const toggleSection = (section) => {
    setActiveSection(activeSection === section ? null : section);
  };

  return (
    <div className="privacy-policy-container">
      <div className="privacy-header">
        <h1>Privacy Policy</h1>
        <p className="effective-date">Effective Date: June 29, 2022</p>
      </div>

      <div className="privacy-content">
        <section className="policy-section">
          <h2>1. Introduction</h2>
          <p>
            Welcome to Green Bunch Group. Green Bunch Group operates RPS Rudrom. Our Privacy Policy governs your visit to RPS Rudrom, and explains how we collect, safeguard and disclose information that results from your use of our Service.
          </p>
          <p>
            We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
          </p>
        </section>

        <section className="policy-section">
          <h2>2. Definitions</h2>
          <div className="definitions-list">
            <div className="definition-item">
              <strong>SERVICE</strong>
              <p>means the RPS Rudrom website operated by Green Bunch Group.</p>
            </div>
            <div className="definition-item">
              <strong>PERSONAL DATA</strong>
              <p>means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
            </div>
            <div className="definition-item">
              <strong>USAGE DATA</strong>
              <p>is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</p>
            </div>
            <div className="definition-item">
              <strong>COOKIES</strong>
              <p>are small files stored on your device (computer or mobile device).</p>
            </div>
            <div className="definition-item">
              <strong>DATA CONTROLLER</strong>
              <p>means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed.</p>
            </div>
            <div className="definition-item">
              <strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong>
              <p>means any natural or legal person who processes the data on behalf of the Data Controller.</p>
            </div>
          </div>
        </section>

        <section className="policy-section">
          <h2>3. Information Collection and Use</h2>
          <p>
            We collect several different types of information for various purposes to provide and improve our Service to you.
          </p>
        </section>

        <section className="policy-section">
          <h2>4. Types of Data Collected</h2>
          
          <div className="data-type">
            <h3>Personal Data</h3>
            <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</p>
            <ul>
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Address, Country, State, Province, ZIP/Postal code, City</li>
              <li>Cookies and Usage Data</li>
            </ul>
            <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.</p>
          </div>

          <div className="data-type">
            <h3>Usage Data</h3>
            <p>
              We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>
          </div>

          <div className="data-type">
            <h3>Location Data</h3>
            <p>
              We may use and store information about your location if you give us permission to do so ("Location Data"). We use this data to provide features of our Service, to improve and customize our Service. You can enable or disable location services when you use our Service at any time by way of your device settings.
            </p>
          </div>

          <div className="data-type">
            <h3>Tracking Cookies Data</h3>
            <p>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information. Examples of Cookies we use:</p>
            <ul>
              <li><strong>Session Cookies:</strong> We use Session Cookies to operate our Service.</li>
              <li><strong>Preference Cookies:</strong> We use Preference Cookies to remember your preferences and various settings.</li>
              <li><strong>Security Cookies:</strong> We use Security Cookies for security purposes.</li>
              <li><strong>Advertising Cookies:</strong> Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</li>
            </ul>
          </div>
        </section>

        <section className="policy-section">
          <h2>5. Use of Data</h2>
          <p>Green Bunch Group uses the collected data for various purposes:</p>
          <ul>
            <li>To provide and maintain our Service</li>
            <li>To notify you about changes to our Service</li>
            <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
            <li>To provide customer support</li>
            <li>To gather analysis or valuable information so that we can improve our Service</li>
            <li>To monitor the usage of our Service</li>
            <li>To detect, prevent and address technical issues</li>
            <li>To fulfill any other purpose for which you provide it</li>
            <li>To carry out our obligations and enforce our rights arising from any contracts entered into between you and us</li>
            <li>To provide you with news, special offers and general information about other goods, services and events</li>
          </ul>
        </section>

        <section className="policy-section">
          <h2>6. Retention of Data</h2>
          <p>
            We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
          </p>
        </section>

        <section className="policy-section">
          <h2>7. Transfer of Data</h2>
          <p>
            Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.
          </p>
          <p>
            Green Bunch Group will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.
          </p>
        </section>

        <section className="policy-section">
          <h2>8. Disclosure of Data</h2>
          <p>We may disclose personal information that we collect, or you provide:</p>
          <ul>
            <li><strong>Business Transaction:</strong> If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.</li>
            <li>To our subsidiaries and affiliates</li>
            <li>To contractors, service providers, and other third parties we use to support our business</li>
            <li>To fulfill the purpose for which you provide it</li>
            <li>With your consent in any other cases</li>
            <li>If we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others</li>
          </ul>
        </section>

        <section className="policy-section">
          <h2>9. Security of Data</h2>
          <p>
            The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
          </p>
        </section>

        <section className="policy-section">
          <h2>10. Your Data Protection Rights Under GDPR</h2>
          <p>
            If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights. In certain circumstances, you have the following data protection rights:
          </p>
          <ul>
            <li>The right to access, update or to delete the information we have on you</li>
            <li>The right of rectification</li>
            <li>The right to object</li>
            <li>The right of restriction</li>
            <li>The right to data portability</li>
            <li>The right to withdraw consent</li>
          </ul>
        </section>

        <section className="policy-section">
          <h2>11. Your Data Protection Rights under CalOPPA</h2>
          <p>According to CalOPPA we agree to the following:</p>
          <ul>
            <li>Users can visit our site anonymously</li>
            <li>Our Privacy Policy link includes the word "Privacy", and can easily be found on the home page of our website</li>
            <li>Users will be notified of any privacy policy changes on our Privacy Policy Page</li>
            <li>Users are able to change their personal information by emailing us</li>
          </ul>
          <p>
            <strong>Our Policy on "Do Not Track" Signals:</strong> We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place.
          </p>
        </section>

        <section className="policy-section">
          <h2>12. Your Data Protection Rights under CCPA</h2>
          <p>
            If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. We don't sell or rent your personal information to any third parties for any purpose.
          </p>
        </section>

        <section className="policy-section">
          <h2>13. Children's Privacy</h2>
          <p>
            Our Services are not intended for use by children under the age of 18. We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us.
          </p>
        </section>

        <section className="policy-section">
          <h2>14. Links to Other Sites</h2>
          <p>
            Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
          </p>
        </section>

        <section className="policy-section">
          <h2>15. Changes to This Privacy Policy</h2>
          <p>
            We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update "effective date" at the top of this Privacy Policy.
          </p>
        </section>

        <section className="policy-section contact-section">
          <h2>16. Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, please contact us:</p>
          <div className="contact-info">
            <p><strong>Green Bunch Group</strong></p>
            <p>RPS Rudrom</p>
            <p>Email: contact@rpsrudrom.in</p>
          </div>
        </section>
      </div>

      <div className="privacy-footer">
        <p>Last Updated: June 29, 2022</p>
        <p>© 2022 Green Bunch Group. All rights reserved.</p>
      </div>
    </div>
  );
};

export default PrivacyPolicy;